services:
  php:
    build:
      context: ./infra/docker/php
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: pdp-prep-php
    volumes:
      - ./:/var/www/pdp
    working_dir: /var/www/pdp
    expose:
      - ${DOCKER_PHP_FPM_PORT:-"9000"}
    command: php-fpm
    networks:
      - pdp-prep
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]   # just tests configuration and that the binary works
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:1.28.0-alpine
    container_name: pdp-prep-nginx
    volumes:
      - ./:/var/www/pdp
      - ./infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${DOCKER_NGINX_BIND_PORT:-"8080:80"}
    depends_on:
      php:
        condition: service_healthy
    networks:
      - pdp-prep
    env_file:
      - .env
  
  tools:
    image: node:22-alpine
    container_name: pdp-prep-tools
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - pdp-prep
    command: >
      sh -c "
        npm install -g autocannon &&
        tail -f /dev/null
      "

networks:
  pdp-prep:
    driver: bridge