apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name laravel.local;

        root /var/www/laravel/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_read_timeout 300;
        }
    }
