apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-fpm-low-config
data:
  default.conf: |
    server {
        listen 80;
        server_name fpm-low.local;

        root /var/www/pdp;
        index index.php;

        # Обработка PHP файлов - передаем в PHP-FPM
        location ~ \.php$ {
            fastcgi_pass php-service-fpm-low:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/pdp/shared/$fastcgi_script_name;
            fastcgi_read_timeout 300;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fpm-low
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-fpm-low
  template:
    metadata:
      labels:
        app: nginx-fpm-low
    spec:
      containers:
        - name: nginx
          image: nginx:1.28.0-alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-fpm-low-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-fpm-low
spec:
  selector:
    app: nginx-fpm-low
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: LoadBalancer

