apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-service-fpm-mid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-service-fpm-mid
  template:
    metadata:
      labels:
        app: php-service-fpm-mid
    spec:
      containers:
        - name: php-fpm
          image: pdp-prep/php-fpm-mid
          ports:
            - containerPort: 9000
              name: php-fpm
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
          env:
            - name: PHP_FPM_LISTEN
              value: "0.0.0.0:9000"
        - name: php-fpm-exporter
          image: hipages/php-fpm_exporter:latest
          ports:
            - containerPort: 9253
              name: metrics
          args:
            - '--phpfpm.scrape-uri=tcp://127.0.0.1:9000/status'
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: php-service-fpm-mid
spec:
  selector:
    app: php-service-fpm-mid
  ports:
    - port: 9000
      name: php-fpm
      targetPort: 9000
    - port: 9253
      name: metrics
      targetPort: 9253
  type: ClusterIP

