apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
stringData:
  APP_KEY: base64:cvSWp+z6OOSKLH/fM3VYmNqaQ9hWxu2pRhg+SIFQ4Ik=
  DB_PASSWORD: ""
  REDIS_PASSWORD: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
